#!/usr/bin/env python3
"""
Phase 5A control: decompose the DS_1mode_10M vs Kerr_220_0M unpaired residual
into prior-width vs data-driven contributions.

Hypothesis under test
---------------------
The 18/20 positive-median asymmetry observed in the unpaired analysis may be
mechanically generated by the DS_1mode_10M f_t_0 prior being much wider than
the Kerr_220_0M-derived f_220 distribution. When DS is prior-dominated, its
median sits near the prior centre (high frequency); subtracting a tight Kerr
median that lies at lower frequency yields a large positive residual that
reflects the prior, not the data.

This script computes per-event diagnostics that disentangle the two effects:

  1. DS informativeness            - q95-q05 width vs the DS prior support.
  2. Kerr informativeness          - q95-q05 width of the derived f_220.
  3. Width ratio                    - sigma_DS / sigma_Kerr.
  4. Width-matched residual         - residual computed only on DS samples
                                      that fall inside the Kerr [q05, q95]
                                      band (prior tails removed).
  5. Reverse-restricted residual    - Kerr restricted to DS [q05, q95].
  6. CDF-at-Kerr-median            - F_DS(median_Kerr); 0.5 = DS centred on
                                      Kerr median; >0.5 = DS biased low;
                                      <0.5 = DS biased high.
  7. Bucketed re-tally              - sign of residual stratified by DS width.

It writes a per-event CSV and a JSON summary with the bucketed counts.

Caveats
-------
This is still a unpaired comparison. The control does not turn it into a
joint residual; it only quantifies how much of the original asymmetry is a
mechanical consequence of the prior-shape mismatch.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import h5py
import numpy as np
import pandas as pd

DEFAULT_DATASET = "GWTC3_rerun_PROD1/posterior_samples"
DEFAULT_SEED = 42
DEFAULT_N_DRAW = 50_000

DS_FIELDS = ("f_t_0", "tau_t_0")
KERR_FIELDS = ("Mf", "final_spin")

FORMULA = "Momega_R=1.5251-1.1568*(1-chi)^0.1292; f_Hz=32314*Momega_R/Mf"

# Bucketing thresholds for DS posterior informativeness (q95-q05 of f_t_0).
# These are reported alongside results; nothing is filtered out.
DS_WIDTH_BUCKETS_HZ = (100.0, 300.0, 600.0)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cohort-csv", required=True)
    ap.add_argument("--out-csv", required=True)
    ap.add_argument("--out-json", required=True)
    ap.add_argument("--dataset", default=DEFAULT_DATASET)
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED)
    ap.add_argument("--n-draw", type=int, default=DEFAULT_N_DRAW)
    return ap.parse_args()


def read_fields(path: Path, dataset: str, fields: tuple[str, ...]) -> dict[str, np.ndarray]:
    with h5py.File(path, "r") as h5:
        dset = h5[dataset]
        return {f: np.asarray(dset.fields(f)[:], dtype=float) for f in fields}


def kerr_f220(mf: np.ndarray, chi: np.ndarray) -> np.ndarray:
    momega = 1.5251 - 1.1568 * np.power(1.0 - chi, 0.1292)
    return 32314.0 * momega / mf


def safe_quantiles(x: np.ndarray, qs: tuple[float, ...]) -> dict[str, float]:
    return {f"q{int(round(q*100)):02d}": float(np.quantile(x, q)) for q in qs}


def width_bucket(w: float) -> str:
    if w < DS_WIDTH_BUCKETS_HZ[0]:
        return "narrow_lt100Hz"
    if w < DS_WIDTH_BUCKETS_HZ[1]:
        return "moderate_100_300Hz"
    if w < DS_WIDTH_BUCKETS_HZ[2]:
        return "wide_300_600Hz"
    return "prior_dominated_gte600Hz"


def per_event(row: Any, dataset: str, rng: np.random.Generator, n_draw: int) -> dict[str, Any]:
    eid = str(row.event_id).strip()
    ds_path = Path(str(row.ds_path).strip())
    kerr_path = Path(str(row.kerr_path).strip())

    ds = read_fields(ds_path, dataset, DS_FIELDS)
    ke = read_fields(kerr_path, dataset, KERR_FIELDS)

    f_obs_all = ds["f_t_0"]
    f_obs_all = f_obs_all[np.isfinite(f_obs_all)]

    mf = ke["Mf"]; chi = ke["final_spin"]
    keep = np.isfinite(mf) & np.isfinite(chi) & (mf > 0) & ((1 - chi) >= 0)
    mf = mf[keep]; chi = chi[keep]
    f_kerr_all = kerr_f220(mf, chi)
    f_kerr_all = f_kerr_all[np.isfinite(f_kerr_all)]

    if f_obs_all.size == 0 or f_kerr_all.size == 0:
        raise ValueError(f"{eid}: empty samples after cleaning")

    # Original-style joint draws: independent same-size resampling.
    ds_idx = rng.integers(0, f_obs_all.size, size=n_draw)
    kerr_idx = rng.integers(0, f_kerr_all.size, size=n_draw)
    f_obs = f_obs_all[ds_idx]
    f_kerr = f_kerr_all[kerr_idx]
    residual = f_obs - f_kerr

    # ---- Posterior shapes ----
    ds_q = safe_quantiles(f_obs, (0.05, 0.25, 0.5, 0.75, 0.95))
    ke_q = safe_quantiles(f_kerr, (0.05, 0.25, 0.5, 0.75, 0.95))
    ds_width_90 = ds_q["q95"] - ds_q["q05"]
    ke_width_90 = ke_q["q95"] - ke_q["q05"]
    ds_iqr = ds_q["q75"] - ds_q["q25"]
    ke_iqr = ke_q["q75"] - ke_q["q25"]
    sigma_ratio = float(f_obs.std(ddof=0) / f_kerr.std(ddof=0))
    iqr_ratio = float(ds_iqr / ke_iqr) if ke_iqr > 0 else float("nan")

    # ---- Original residual ----
    res_q50_full = float(np.median(residual))
    p_full = float(np.mean(residual > 0))

    # ---- Width-matched: DS restricted to Kerr 90% band ----
    band_lo, band_hi = ke_q["q05"], ke_q["q95"]
    mask = (f_obs_all >= band_lo) & (f_obs_all <= band_hi)
    ds_in_band_frac = float(mask.mean())
    if mask.sum() > 50:
        f_obs_band = f_obs_all[mask]
        idx = rng.integers(0, f_obs_band.size, size=n_draw)
        f_obs_b = f_obs_band[idx]
        residual_b = f_obs_b - f_kerr
        res_q50_band = float(np.median(residual_b))
        p_band = float(np.mean(residual_b > 0))
    else:
        res_q50_band = float("nan")
        p_band = float("nan")

    # ---- Reverse: Kerr restricted to DS 90% band ----
    rband_lo, rband_hi = ds_q["q05"], ds_q["q95"]
    rmask = (f_kerr_all >= rband_lo) & (f_kerr_all <= rband_hi)
    ke_in_band_frac = float(rmask.mean())
    if rmask.sum() > 50:
        f_k_band = f_kerr_all[rmask]
        idx = rng.integers(0, f_k_band.size, size=n_draw)
        f_k_b = f_k_band[idx]
        residual_r = f_obs - f_k_b
        res_q50_rev = float(np.median(residual_r))
        p_rev = float(np.mean(residual_r > 0))
    else:
        res_q50_rev = float("nan")
        p_rev = float("nan")

    # ---- Distributional diagnostic: F_DS at Kerr median ----
    # If F_DS(f_Kerr_median) ~ 0.5 the DS posterior is centred on the Kerr median.
    # If it is < 0.5 the DS mass sits above f_Kerr_median (positive bias mechanically).
    cdf_ds_at_kerr_med = float(np.mean(f_obs_all <= ke_q["q50"]))

    return {
        "event_id": eid,
        # Posterior shapes
        "ds_n_samples": int(f_obs_all.size),
        "kerr_n_samples": int(f_kerr_all.size),
        "ds_q05_hz": ds_q["q05"], "ds_q50_hz": ds_q["q50"], "ds_q95_hz": ds_q["q95"],
        "kerr_q05_hz": ke_q["q05"], "kerr_q50_hz": ke_q["q50"], "kerr_q95_hz": ke_q["q95"],
        "ds_width_90_hz": ds_width_90, "kerr_width_90_hz": ke_width_90,
        "ds_iqr_hz": ds_iqr, "kerr_iqr_hz": ke_iqr,
        "sigma_ratio_ds_over_kerr": sigma_ratio,
        "iqr_ratio_ds_over_kerr": iqr_ratio,
        "ds_width_bucket": width_bucket(ds_width_90),
        # Residuals
        "residual_q50_full_hz": res_q50_full,
        "p_residual_gt_0_full": p_full,
        "residual_q50_dsband_hz": res_q50_band,
        "p_residual_gt_0_dsband": p_band,
        "ds_in_kerr_band_frac": ds_in_band_frac,
        "residual_q50_kerrband_hz": res_q50_rev,
        "p_residual_gt_0_kerrband": p_rev,
        "kerr_in_ds_band_frac": ke_in_band_frac,
        # Distributional asymmetry diagnostic
        "cdf_ds_at_kerr_median": cdf_ds_at_kerr_med,
    }


def bucket_summary(df: pd.DataFrame, residual_col: str) -> dict[str, dict[str, int]]:
    out: dict[str, dict[str, int]] = {}
    for bucket, sub in df.groupby("ds_width_bucket"):
        vals = sub[residual_col].dropna()
        out[bucket] = {
            "n_events": int(len(sub)),
            "n_with_residual": int(len(vals)),
            "n_positive": int((vals > 0).sum()),
            "n_negative": int((vals < 0).sum()),
            "n_zero_or_nan": int(len(sub) - len(vals)) + int((vals == 0).sum()),
            "median_of_medians_hz": float(vals.median()) if len(vals) else float("nan"),
        }
    return out


def main() -> int:
    args = parse_args()
    cohort = pd.read_csv(args.cohort_csv)
    cohort["event_id"] = cohort["event_id"].astype(str).str.strip()

    rng = np.random.default_rng(args.seed)
    rows = [per_event(row, args.dataset, rng, args.n_draw) for row in cohort.itertuples(index=False)]
    df = pd.DataFrame(rows)

    out_csv = Path(args.out_csv); out_json = Path(args.out_json)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_csv, index=False)

    def tally(col: str) -> dict[str, Any]:
        vals = df[col].dropna()
        return {
            "n_events_with_value": int(len(vals)),
            "n_positive": int((vals > 0).sum()),
            "n_negative": int((vals < 0).sum()),
            "median_hz": float(vals.median()) if len(vals) else float("nan"),
        }

    summary = {
        "script": "tools/phase5a_control_widthmatched_residual.py",
        "cohort_csv": args.cohort_csv,
        "out_csv": str(out_csv),
        "n_events": int(len(df)),
        "formula": FORMULA,
        "seed": args.seed,
        "n_draw": args.n_draw,
        "ds_width_buckets_hz_thresholds": list(DS_WIDTH_BUCKETS_HZ),
        "global": {
            "full_residual": tally("residual_q50_full_hz"),
            "dsband_residual": tally("residual_q50_dsband_hz"),
            "kerrband_residual": tally("residual_q50_kerrband_hz"),
        },
        "by_ds_width_bucket": {
            "full": bucket_summary(df, "residual_q50_full_hz"),
            "dsband": bucket_summary(df, "residual_q50_dsband_hz"),
            "kerrband": bucket_summary(df, "residual_q50_kerrband_hz"),
        },
        "shape_diagnostics": {
            "median_sigma_ratio_ds_over_kerr": float(df["sigma_ratio_ds_over_kerr"].median()),
            "median_iqr_ratio_ds_over_kerr": float(df["iqr_ratio_ds_over_kerr"].median()),
            "median_cdf_ds_at_kerr_median": float(df["cdf_ds_at_kerr_median"].median()),
            "n_events_cdf_below_half": int((df["cdf_ds_at_kerr_median"] < 0.5).sum()),
            "n_events_cdf_above_half": int((df["cdf_ds_at_kerr_median"] > 0.5).sum()),
        },
        "method_caveat": (
            "The width-matched residuals restrict DS samples to the Kerr 90% band "
            "(or Kerr to the DS band) but do not produce a joint sample-by-sample "
            "residual posterior. They are a sensitivity decomposition of the "
            "original unpaired comparison."
        ),
    }
    out_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print("wrote:", out_csv)
    print("wrote:", out_json)
    print()
    print(f"events: {len(df)}")
    print(f"median sigma_DS/sigma_Kerr: {summary['shape_diagnostics']['median_sigma_ratio_ds_over_kerr']:.2f}")
    print(f"median CDF_DS(f_kerr_med):   {summary['shape_diagnostics']['median_cdf_ds_at_kerr_median']:.3f}  (0.5 = symmetric)")
    print()
    for col, label in (
        ("residual_q50_full_hz", "FULL          (no restriction)"),
        ("residual_q50_dsband_hz", "DS in KERR 90%"),
        ("residual_q50_kerrband_hz", "KERR in DS 90%"),
    ):
        vals = df[col].dropna()
        n_pos = int((vals > 0).sum()); n_neg = int((vals < 0).sum())
        med = float(vals.median()) if len(vals) else float("nan")
        print(f"  {label:32s}  pos/neg = {n_pos:2d}/{n_neg:2d}   median residual = {med:+8.2f} Hz")
    print()
    print("by DS width bucket (full residual):")
    for b, r in summary["by_ds_width_bucket"]["full"].items():
        print(f"  {b:30s}  n={r['n_events']:2d}  pos={r['n_positive']:2d}  neg={r['n_negative']:2d}  median={r['median_of_medians_hz']:+8.2f} Hz")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
